# Generated by Django 6.0.3 on 2026-03-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('GASTO', 'Gasto')], max_length=10)),
                ('monto_total_real', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('archivo_factura', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('es_fiscal', models.BooleanField(default=False)),
            ],
        ),
    ]
