# Generated by Django 6.0.3 on 2026-03-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('MERCADERIA', 'Compra de Mercadería'), ('SERVICIOS', 'Servicios (Luz, Agua, Internet)'), ('ALQUILER', 'Alquiler'), ('SUELDOS', 'Sueldos'), ('OTROS', 'Otros Gastos')], default='MERCADERIA', max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_total_real', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('archivo_factura', models.FileField(blank=True, null=True, upload_to='facturas/')),
            ],
        ),
    ]
