# Generated by Django 6.0.3 on 2026-03-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('SERVICIOS', 'Servicios (Luz, Gas, Agua)'), ('MANTENIMIENTO', 'Mantenimiento / Limpieza'), ('SUELDOS', 'Sueldos / Adelantos'), ('MERCADERIA', 'Compra Mercadería'), ('VARIOS', 'Gastos Varios')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
    ]
