# Generated by Django 6.0.3 on 2026-03-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_gastogeneral_delete_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastogeneral',
            name='tipo',
            field=models.CharField(choices=[('FIJO', 'Gasto Fijo'), ('VARIABLE', 'Gasto Variable')], default='VARIABLE', max_length=10),
        ),
    ]
