# Generated by Django 6.0.3 on 2026-03-03 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_gastogeneral_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastogeneral',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
