# Generated by Django 6.0.3 on 2026-03-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_gastogeneral_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastogeneral',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Mercado Pago'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20),
        ),
    ]
