# Generated by Django 6.0.3 on 2026-03-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_gastogeneral_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock_actual', models.IntegerField(default=0)),
                ('umbral_minimo', models.IntegerField(default=5, help_text='Avisar cuando el stock sea menor a este número')),
            ],
        ),
    ]
